/*
 * @Date: 2026-09-11 18:52:55
 * @LastEditors: zhouke
 * @LastEditTime: 2026-09-14 20:48:37
 * @FilePath: \xiaozhi-esp32\main\boards\waveshare\esp32-p4-nano\config.h
 */
#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <driver/uart.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_13
#define AUDIO_I2S_GPIO_WS GPIO_NUM_10
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_12
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_11
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_9

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_53
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_7
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_8
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO        GPIO_NUM_35

#define PRODUCTION_MODBUS_UART_PORT   UART_NUM_1
#define PRODUCTION_MODBUS_UART_TX_PIN GPIO_NUM_20
#define PRODUCTION_MODBUS_UART_RX_PIN GPIO_NUM_21

#define DISPLAY_WIDTH 800
#define DISPLAY_HEIGHT 1280

#define LCD_BIT_PER_PIXEL          (16)
#define PIN_NUM_LCD_RST            GPIO_NUM_NC

#define DELAY_TIME_MS                      (3000)
#define LCD_MIPI_DSI_LANE_NUM          (2)    // 2 data lanes

#define MIPI_DSI_PHY_PWR_LDO_CHAN          (3)
#define MIPI_DSI_PHY_PWR_LDO_VOLTAGE_MV    (2500)

#define DISPLAY_SWAP_XY false
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

/* Herdsman UI layout switches: set to 0 to give the panel space to the chat area. */
#define HERDSMAN_UI_SHOW_LEFT_LOGO     1
#define HERDSMAN_UI_SHOW_RIGHT_BUTTONS 1
#if (HERDSMAN_UI_SHOW_LEFT_LOGO != 0 && HERDSMAN_UI_SHOW_LEFT_LOGO != 1) || \
    (HERDSMAN_UI_SHOW_RIGHT_BUTTONS != 0 && HERDSMAN_UI_SHOW_RIGHT_BUTTONS != 1)
#error "Herdsman UI visibility switches must be 0 or 1"
#endif

/* Herdsman UI color theme selection. */
#define HERDSMAN_UI_THEME_RANCH_ORANGE 0
#define HERDSMAN_UI_THEME_TECH_BLUE    1
#define HERDSMAN_UI_THEME_DARK         2
#define HERDSMAN_UI_THEME              HERDSMAN_UI_THEME_DARK

#if HERDSMAN_UI_THEME == HERDSMAN_UI_THEME_RANCH_ORANGE
#define HERDSMAN_UI_COLOR_ACCENT              0xE84A0C
#define HERDSMAN_UI_COLOR_ACCENT_PRESSED      0xC83D08
#define HERDSMAN_UI_COLOR_ON_ACCENT           0xFFFFFF
#define HERDSMAN_UI_COLOR_TEXT                0x15191F
#define HERDSMAN_UI_COLOR_MUTED_TEXT          0x73777D
#define HERDSMAN_UI_COLOR_ICON                0x3F4C5B
#define HERDSMAN_UI_COLOR_PAGE                0xEEF0F2
#define HERDSMAN_UI_COLOR_CARD                0xFFFFFF
#define HERDSMAN_UI_COLOR_CARD_BORDER         0xFFFFFF
#define HERDSMAN_UI_COLOR_DIVIDER             0xD9DDE0
#define HERDSMAN_UI_COLOR_SHADOW              0x7F858B
#define HERDSMAN_UI_COLOR_USER_BUBBLE         0xE1E3E5
#define HERDSMAN_UI_COLOR_ASSISTANT_BUBBLE    0xFFFFFF
#define HERDSMAN_UI_COLOR_SYSTEM_BUBBLE       0xFFF1E8
#define HERDSMAN_UI_COLOR_ASSISTANT_AVATAR_BG 0xFFFFFF
#define HERDSMAN_UI_COLOR_USER_AVATAR_BG      0xC7C9CB
#define HERDSMAN_UI_COLOR_USER_AVATAR_FG      0x787B7F
#define HERDSMAN_UI_COLOR_SUCCESS             0x279B55
#define HERDSMAN_UI_COLOR_DANGER              0xD93333
#elif HERDSMAN_UI_THEME == HERDSMAN_UI_THEME_TECH_BLUE
#define HERDSMAN_UI_COLOR_ACCENT              0x1769E0
#define HERDSMAN_UI_COLOR_ACCENT_PRESSED      0x0E4FAF
#define HERDSMAN_UI_COLOR_ON_ACCENT           0xFFFFFF
#define HERDSMAN_UI_COLOR_TEXT                0x152033
#define HERDSMAN_UI_COLOR_MUTED_TEXT          0x667085
#define HERDSMAN_UI_COLOR_ICON                0x344054
#define HERDSMAN_UI_COLOR_PAGE                0xEDF3FA
#define HERDSMAN_UI_COLOR_CARD                0xFFFFFF
#define HERDSMAN_UI_COLOR_CARD_BORDER         0xDCE7F5
#define HERDSMAN_UI_COLOR_DIVIDER             0xD6E0EC
#define HERDSMAN_UI_COLOR_SHADOW              0x6680A0
#define HERDSMAN_UI_COLOR_USER_BUBBLE         0xD9E8FF
#define HERDSMAN_UI_COLOR_ASSISTANT_BUBBLE    0xFFFFFF
#define HERDSMAN_UI_COLOR_SYSTEM_BUBBLE       0xE8F1FF
#define HERDSMAN_UI_COLOR_ASSISTANT_AVATAR_BG 0xE8F1FF
#define HERDSMAN_UI_COLOR_USER_AVATAR_BG      0xC9D8EA
#define HERDSMAN_UI_COLOR_USER_AVATAR_FG      0x52657A
#define HERDSMAN_UI_COLOR_SUCCESS             0x18864B
#define HERDSMAN_UI_COLOR_DANGER              0xCF3B3B
#elif HERDSMAN_UI_THEME == HERDSMAN_UI_THEME_DARK
#define HERDSMAN_UI_COLOR_ACCENT              0xFF7A45
#define HERDSMAN_UI_COLOR_ACCENT_PRESSED      0xD95B2B
#define HERDSMAN_UI_COLOR_ON_ACCENT           0xFFFFFF
#define HERDSMAN_UI_COLOR_TEXT                0xF2F4F7
#define HERDSMAN_UI_COLOR_MUTED_TEXT          0xA7ADB7
#define HERDSMAN_UI_COLOR_ICON                0xD0D5DD
#define HERDSMAN_UI_COLOR_PAGE                0x11151B
#define HERDSMAN_UI_COLOR_CARD                0x20262E
#define HERDSMAN_UI_COLOR_CARD_BORDER         0x343C47
#define HERDSMAN_UI_COLOR_DIVIDER             0x3B4450
#define HERDSMAN_UI_COLOR_SHADOW              0x000000
#define HERDSMAN_UI_COLOR_USER_BUBBLE         0x39424D
#define HERDSMAN_UI_COLOR_ASSISTANT_BUBBLE    0x282F38
#define HERDSMAN_UI_COLOR_SYSTEM_BUBBLE       0x3A2A24
#define HERDSMAN_UI_COLOR_ASSISTANT_AVATAR_BG 0x343C47
#define HERDSMAN_UI_COLOR_USER_AVATAR_BG      0x4A5563
#define HERDSMAN_UI_COLOR_USER_AVATAR_FG      0xD0D5DD
#define HERDSMAN_UI_COLOR_SUCCESS             0x4CCB7F
#define HERDSMAN_UI_COLOR_DANGER              0xE05252
#else
#error "Unsupported HERDSMAN_UI_THEME"
#endif

#endif // _BOARD_CONFIG_H_
